default_language_version:
  python: python3.11

repos:

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        types: [python]
        args: [--strict]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        types: [python]
        args: [--check]
